---
title: "model_train_with_multiple_learners"
author: "Peian"
date: '2022-07-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source( "data_loader.R" )
temp = data_loader( Hour = 361)
data19 = temp$data_19
ac19 = temp$ac_19
# removing  "pump.outlet"
data19 = data19[ , -which(names(data19) == "O2.in.offgas.." ) ] 
nzv = nearZeroVar(data19, saveMetrics= TRUE)
nzv = nearZeroVar(data19)
data19 = data19[, -nzv]
data19 = data19[,-c(53:59)]
```
### Selecting the data closest to real data
```{r , echo = FALSE}
set.seed(825)
index = vector( len = nrow(ac19) )
for ( i in 1:nrow(ac19) )
{
  index[i] = which( abs( ac19$EFT[i] - data19$EFT_H ) == min( abs(   ac19$EFT[i] - data19$EFT_H) ) )
  
}
data19 = data19[,-1]
train = data19[-index , ]
test = data19[index,]
```

# Go
## Pre-process
```{r}
set.seed(825)
cpu = detectCores()
tuneLength = 4
repeats = 2
folds = 3
total = repeats * folds 
result = c() ##  Record for performances
lambdaSearch = seq( 0, 1 , length.out = 10) 
lambdaSearch[2] = 1e-5   ## set a small number to check whether lasso works #
alphaSearch = seq(0,1,10)
# Set the seeds
seeds = vector(mode = "list", length = total+1)
for(i in 1:total) seeds[[i]]= sample.int(n=1000, (total + 1)  )
seeds[[ (total+1) ]]=sample.int(1000, 1)
# Set fitControl for the trControl
fitControl = trainControl( method = "repeatedcv", number = folds, repeats = repeats , search = "random" ,seed = seeds)
```

### Search grid
```{r}
mars_grid = expand.grid( degree = 2:3,  nprune = floor( seq(30, (p-1), by = 1 ) ) )
lasso_grid = expand.grid( lambda = lambdaSearch , alpha = 0)
blasso_grid = expand.grid( lambda = lambdaSearch )
ridge_grid = expand.grid( lambda = lambdaSearch , alpha = 1 )
elastic_grid = expand.grid( lambda = lambdaSearch , alpha = alphaSearch )
m5_grid = expand.grid(pruned = c("Yes"), smoothed = c("Yes"), rules = c("Yes") ) 
```


```{r}
lm = list( method = "lm" )
mars = list( method = 'earth' , tune_grid = mars_grid)
bagMars = list( method = 'bagEarth' )
adaBag = list( method = 'treebag')
cart = list( method = 'rpart')
xgbLinear = list( method = 'xgbLinear') 
xgb = list( method = 'xgbDART')
GpKernel = list( method = 'gaussprRadial')
knn = list( method = 'kknn')
pls = list( method = 'pls')
PolyKernelRLs = list( method = 'krlsPoly')
pcr = list( method = 'pcr')
rf = list( method = 'rf')
svmRadial = list( method = 'svmRadial')
lasso = list( method = 'glmnet' , tune_grid = lasso_grid)
blasso = list( method = 'blasso' , tune_grid = blasso_grid)
ridge = list( method = 'glmnet' , tune_grid = ridge_grid)
elasticNet = list( method = 'glmnet' , tune_grid = elastic_grid)
wrappers = list( lm = lm,mars = mars,adaBag = adaBag,cart = cart, 
                 xgbLinear = xgbLinear,
                 xgb = xgb,GpKernel = GpKernel,knn = knn, pls = pls ,
                 PolyKernelRLs = PolyKernelRLs , pcr = pcr ,
                 rf = rf, svmRadial = svmRadial ,
                 lasso = lasso , #blasso = blasso ,
                 elasticNet = elasticNet )
samples = sample(1:nrow(train) , size = 200 )
models = models_train( train[samples,], wrappers , fitControl , 2 ,test , cpu )
```

### Get importance of variables
```{r}
nm = names(train)[1:(ncol(train)-1)]
vimp = c()
models_rmse = c()
models_mean_per_error = c()
for (model in models)
{
  importance = getVarImp( model , nm)
  vimp = cbind( vimp , importance)
  models_rmse = c( models_rmse , model$rmse)
  models_mean_per_error = c( models_mean_per_error , model$mean_per_error )
}
colnames( vimp ) = names( models )
rownames( vimp ) = nm
names(models_rmse) = names(models)
names(models_mean_per_error) = names(models)
```

```{r}
temp =  sum( models_rmse ) / models_rmse 
final_weights = as.matrix( temp / sum(temp) )
final_vimp =  ( as.matrix(vimp) %*% final_weights )
final_vimp = final_vimp[ order(final_vimp , decreasing = TRUE) , ]
write.csv(final_vimp, file ="final_importance", row.names =TRUE )
```

### get performance plot
```{r}
collect = list()
for ( model in models )
{
  collect = c( collect , temp = list(model$model) )
}
names(collect) = names(models)
resamps = resamples( collect)
bwplot(resamps)
```


